# Specific configurations for kube-prometheus-stack for seyoawe app.

kube-prometheus-stack:

  # Prometheus
  prometheus:
    prometheusSpec:
      scrapeInterval: "30s"
      evaluationInterval: "30s"
      retention: "15d"

      # StorageSpec
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 20Gi
      
      # Auto-Discover ServiceMonitors across namespaces
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorNamespaceSelector: {}
      serviceMonitorSelector: {}

      # pick up PodMonitors
      podMonitorSelectorNilUsesHelmValues: false
      podMonitorNamespaceSelector: {}
      podMonitorSelector: {}

      resources:
        requests: 
          cpu: "250m"
          memory: "512Mi"
        limits:
          cpu: "1000m"
          memory: "2Gi"

  # Grafana
  grafana:
    enabled: true
    adminPassword: "admin"

    service:
      type: ClusterIP
      port: 80

    persistence:
      enabled: true
      storageClassName: gp2
      size: 5Gi

    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL 
        downloadDashboards: true

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"     
    
    ingress:
      enabled: true
      ingressClassName: alb
      annotations:
        alb.ingress.kubernetes.io/scheme: "internet-facing"
        alb.ingress.kubernetes.io/target-type: "ip"
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      path: /
      pathType: Prefix

  kube-state-metrics:
    enabled: true

  nodeExporter:
    enabled: true
    
  alertmanager:
    enabled: true  
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: gp2
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi
  
  # Default alert rules
  defaultRules:
    create: true
    rules: 
      alertmanager: true
      etcd: true
      configReloaders: true
      general: true
      kubeApiserverAvailability: true
      kubeApiserverBurnrate: true
      kubeApiserverHistogram: true
      kubeApiserverSlos: true
      kubeControllerManager: false   # not accessible in EKS
      kubelet: true
      kubeProxy: false               # not accessible in EKS
      kubeSchedulerAlerting: false   # not accessible in EKS
      kubeStateMetrics: true
      kubeStorageOperations: true
      kubernetesAbsent: true
      kubernetesApps: true
      kubernetesResources: true
      kubernetesStorage: true
      kubernetesSystem: true
      nodeExporterAlerting: true
      nodeExporterRecording: true
      prometheus: true
      prometheusOperator: true

dashboards:
  d15661:
    json: ""