apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-engine-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-engine
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
data: