apiVersion: apps/v1
kind: StatefulSet
metadata: 
  name: {{ .Release.Name }}-engine
  namespace: {{ .Release.Namespace }}
  labels: 
    app: {{ .Release.Name }}-engine
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
spec: 
  serviceName: {{ .Release.Name }}-engine-headless
  replicas: {{ .Values.replicaCount }}
  selector: 
    matchLabels:
      app: {{ .Release.Name }}-engine
  updateStrategy:
    type: RollingUpdate 
  template: 
    metadata:
      labels:
        app: {{ .Release.Name }}-engine
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001

      containers:
        - name: engine
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}" #"assafnw/seyoawe-engine:version"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP 
          
          envFrom:
            - configMapRef: 
                name: {{ .Release.Name }}-engine-config
          
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          
          volumeMounts:
            - name: lifetimes
              mountPath: /app/lifetimes
            - name: logs
              mountPath: /app/logs
            - name: workflows
              mountPath: /app/workflows
            - name: modules
              mountPath: /app/modules

      volumes:
        - name: lifetimes
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-lifetimes-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-logs-pvc
        - name: workflows
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-workflows-pvc
        - name: modules
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-modules-pvc