# Deploy the monitoring stack - Grafana + Prometheus.
#
# run the command line:
# ansible-playbook playbook/deploy_monitoring.yaml \
#   -i inventory/hosts.ini
#   -e "environment=prod"
#
# The following environment variables should be provided by github actions:
#  TF_OUTPUT_CLUSTER_NAME --from terraform output
#  GRAFANA_PASSWORD --from repo secrets

- name: Deploy monitoring stack to {{ environment }}
  hosts: local
  gather_facts: false

  roles:
      # validating kubeconfig to deploy monitoring
    - role: eks_auth
    - role: deploy_monitoring