# Deploy the complete seyoawe app to AWS EKS.
# Called after Terraform completed infrastructure deployment.
#
# run this command to run the playbook:
#   ansible-playbook playbooks/deploy_seyoawe.yaml \
#     -i inventory/hosts.ini \
#     -e "deploy_env=prod"
#
# The following deploy_env variables should be provided by github actions:
#  APP_VERSION - the new version that added via github tag
#  TF_OUTPUT_CLUSTER_NAME - from terraform output


- name: Deploy seyoawe to {{ deploy_env | default('prod') }}
  hosts: local
  gather_facts: false

  roles:
      # Install all needed dependencies: kubectl, aws cli, helm
    - role: dependencies
      # aws eks update-kubeconfig and connectivity check 
    - role: eks_auth
    # create efs-sc StorageClass in cluster
    - role: efs_storageclass
    - role: deploy_app
