global: 

# Engine Subchart Values
engine:
  image:
    repository: assafnw/seyoawe-engine
    tag: "" # use: --set engine.image.tag=$VERSION
    pullPolicy: Always

  replicaCount: 1

  service: 
    port: 80
    targetPort: 8080
    healthPort: 9000

  resources:
    requests:
      cpu: "250m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  
  healthCheck:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20

# CLI Subchart Values
cli:
  image:
    repository: assafnw/seyoawe-cli
    tag: "" # must use --set cli.image.tag=$VERSION
    pullPolicy: Always
  
  replicaCount: 1

  service:
    port: 80
    targetPort: 8081

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  
  engineUrl: "http://{{ .Release.Name }}-engine.{{ .Release.Namespace }}.svc.cluster.local"

  healthCheck:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 20

# Ingress
ingress:
  enabled: true 
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: "internet-facing"
    alb.ingress.kubernetes.io/target-type: "ip"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": "80"}]'
    alb.ingress.kubernetes.io/healthcheck-path: "/health"
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: "30"
    alb.ingress.kubernetes.io/success-codes: "200"
    # sticky session for CLI
    alb.ingress.kubernetes.io/target-group-attributes: "stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=86400"

# Shared Storage - EFS
sharedStorage:
  size: 5Gi