apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-cli
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-cli
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-cli
  port: 
    - name: ttyd
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}